### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by raphaelsander** [IntelligenceX/SDK#6]
**First error:**

```bash
sander@Bl4ckC47:~$ python3 ix_search.py 2.intelx.io 49e4ad58-****-****-****-8158551bb30d test.com
Traceback (most recent call last):
  File "ix_search.py", line 101, in <module>
    if not validators.domain(api_domain):
NameError: name 'validators' is not defined
```

**I removed the part of the code that was showing an error, and another error came up:**

```bash
sander@Bl4ckC47:~$ python3 ix_search.py 2.intelx.io 49e4ad58-****-****-****-8158551bb30d test.com
[+]Successful API Authentication. Starting records search.
Traceback (most recent call last):
  File "ix_search.py", line 105, in <module>
    ix_search(api_domain, api_key, selector)
  File "ix_search.py", line 71, in ix_search
    unicode(json.dumps(data, indent=4, default=jsondate), 'UTF-8'),
NameError: name 'unicode' is not defined
```

**Comment by Kleissner** [comment]
We just uploaded the new Python code.
